import os
import sys

SERVER_HOST = "tomato.local"
SERVER_PORT = "3000"
MAX_VALUE = 20
BOARD_ROWS = 7
BOARD_COLUMNS = 7
SERVER_ADDR = f"{SERVER_HOST}:{SERVER_PORT}"
BLOCK_SIZE = 80
BLOCK_CENTER = BLOCK_SIZE / 2

