const SERVER_HOST = "owen.local";
const SERVER_PORT = "3000";
const BLOCK_SIZE = 80;
const MAX_VALUE: 20;
const BOARD_ROWS = 7;
const BOARD_COLUMNS = 7;
const SERVER_HOST = SERVER_HOST;
const SERVER_PORT= SERVER_HOST;
const SERVER_ADDR= SERVER_HOST + "=" + SERVER_PORT;
const BLOCK_SIZE= BLOCK_SIZE;
const BLOCK_CENTER= BLOCK_SIZE / 2

